- name: Set tarball path
  set_fact:
    tarball_path: "{{ fileserver.path }}/{{ zuul.project.short_name }}"

- name: Ensure project directory exists
  file:
    path: "{{ tarball_path }}"
    state: directory
    recurse: yes
    mode: 0775

- name: Upload contents of the artifacts folder
  synchronize:
    src: "{{ zuul.executor.work_root }}/artifacts/"
    dest: "{{ tarball_path }}/"
