- name: Check if project's tools/test-setup.sh exists
  stat:
    path: "src/{{ zuul.project.canonical_name }}/tools/test-setup.sh"
  register: p

- name: Run tools/test-setup.sh
  shell: tools/test-setup.sh
  args:
    chdir: "src/{{ zuul.project.canonical_name }}"
  when:
    - p.stat.exists
    - p.stat.executable
