- hosts: all
  pre_tasks:
    - shell: tox -l
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"
      register: envlist
    - set_fact:
        tox_envlist: 'pep8'
      when: envlist.stdout.find('pep8') != -1
    - set_fact:
        tox_envlist: 'linters'
      when: envlist.stdout.find('linters') != -1
  roles:
    - tox
