- hosts: all
  roles:
    - role: configure-mirrors
      # TODO(mordred) When we have site-local variables, these should go there
      mirror_fqdn: "mirror.{{ nodepool.region | lower }}.{{ nodepool.provider | lower }}.openstack.org"
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
      # TODO(mordred) When we have site-local variables, these should go there
      bindep_command: /usr/bindep-env/bin/bindep
      bindep_fallback: /usr/local/jenkins/common_data/bindep-fallback.txt
    - test-setup
    - revoke-sudo
