- name: Create SSH private key from secret
  copy:
    content: "{{ fileserver.ssh_private_key }}"
    dest: ~/.ssh/tarballs_id_rsa
    mode: 0600

- name: Add tarballs server ssh key
  command: ssh-add ~/.ssh/tarballs_id_rsa

- name: Remove SSH private key from disk
  command: shred ~/.ssh/tarballs_id_rsa

- name: Add tarballs server to inventory
  add_host:
    name: "{{ fileserver.fqdn }}"
    ansible_user: "{{ fileserver.ssh_username }}"

- name: Add tarballs server to known hosts
  known_hosts:
    name: "{{ fileserver.fqdn }}"
    key: "{{ fileserver.ssh_known_hosts }}"
