- name: Require tox_envlist variable - {{ tox_envlist }}
  fail:
    msg: "tox_envlist is required for this role"
  when: tox_envlist is not defined

- name: Create my_tox_environment variable
  set_fact:
    my_tox_environment: "{{ tox_environment_defaults | combine(tox_environment) }}"

- name: Run tox
  args:
    chdir: "{{ zuul_work_dir | default(omit) }}"
  environment: "{{ my_tox_environment }}"
  command: "{{ tox_executable }} -e{{ tox_envlist }} {{ tox_extra_args }}"
