- name: Ensure local tox dir
  file:
    path: "{{ tox_output_log_path }}"
    state: directory
  delegate_to: localhost

- name: Find tox directories to synchronize
  find:
    file_type: directory
    paths: "{{ zuul_work_dir }}/.tox"
    recurse: no
  register: result

- name: check if there is a log directory present
  stat:
    path: "{{ item.path }}/log"
  with_items: "{{ result.files }}"
  register: tox_output_log_stat

- name: debug stat
  debug:
    var: tox_output_log_stat

- name: Collect tox logs
  synchronize:
    src: "{{ item.1.stat.path }}/"
    dest: "{{ tox_output_log_path }}/{{ item.0.path | basename }}"
    mode: pull
    verify_host: true
  when: item.1.stat.exists
  with_together:
    - "{{ result.files }}"
    - "{{ tox_output_log_stat.results }}"
