- name: Register testrepository directory
  stat:
    path: "{{ zuul_work_dir }}/.testrepository"
  register: testrepository_stat

# - name: Process testr artifacts
#   include: process.yaml
#   when:
#     - testrepository_stat.stat.exists
